// <auto-generated />
using System;
using Empresa_API_FINAL.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Empresa_API_FINAL.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    partial class EmpresaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedModels.Deducciones", b =>
                {
                    b.Property<int>("deduccionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deduccionesId"));

                    b.Property<string>("ApellidoDeEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DeduccionPorDaños")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PensionAlimenticia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrestamoBancario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrestamoEmpresario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("empleadoId")
                        .HasColumnType("int");

                    b.Property<string>("nombreDeEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deduccionesId");

                    b.ToTable("deducciones");
                });

            modelBuilder.Entity("SharedModels.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<int?>("celular")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("estadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("fechaDeCierreDeContrato")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaDeContratacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaDeNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("numCedula")
                        .HasColumnType("int");

                    b.Property<int>("numInss")
                        .HasColumnType("int");

                    b.Property<int>("numRuc")
                        .HasColumnType("int");

                    b.Property<string>("primerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("telefono")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("SharedModels.Ingresos", b =>
                {
                    b.Property<int>("IngresosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresosId"));

                    b.Property<string>("ApellidoDeEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Bonificaciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Comisiones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DepreciacionVehiculo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("HorasExtra")
                        .HasColumnType("int");

                    b.Property<decimal?>("OtrosIngresos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RiesgoLaboral")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ViaticoAlimenticio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ViaticoCombustible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nombreDeEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngresosId");

                    b.ToTable("ingresos");
                });

            modelBuilder.Entity("SharedModels.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreDeEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidoDeEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("inns")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ir")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("nominas");
                });

            modelBuilder.Entity("SharedModels.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreDeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
